FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH=/app/grpc_gen/generated:$PYTHONPATH

COPY . /app/

EXPOSE 50052

CMD ["python", "subscription_server.py"]
