services:
  postgresql_subscription_service:
    image: postgres
    container_name: postgresql_subscription_container
    environment:
      POSTGRES_PASSWORD: my_secret_password
      POSTGRES_DB: grpc_database
      POSTGRES_USER: user_1
      PGPORT: 5433
    ports:
      - "5433:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_1 -d grpc_database"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - pjp_mynetwork
    volumes:
      - postgresql_subscription_data:/var/lib/postgresql/data

  postgresql_user_service:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    container_name: postgresql_user_container
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=user_management
    volumes:
      - postgresql_user_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test -d user_management" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - pjp_mynetwork

  postgresql_tasks_service:
    image: postgres
    container_name: postgresql_tasks_container
    environment:
      POSTGRES_USER: tasks
      POSTGRES_PASSWORD: tasks123
      POSTGRES_DB: tasks_db
      PGPORT: 5434
    ports:
      - "5434:5434"
    volumes:
      - postgresql_tasks_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tasks -d tasks_db" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - pjp_mynetwork


  notification_service:
    build:
      context: .
      dockerfile: notification_service/Dockerfile
    container_name: notification_service
    depends_on:
      postgresql_subscription_service:
        condition: service_healthy
      postgresql_user_service:
        condition: service_healthy
      subscription_server_service:
        condition: service_started
      user_server_service:
        condition: service_started
      fastapi_orchestrator_service:
        condition: service_started
      graphql_service:
        condition: service_started
      broker:
        condition: service_healthy
      postgresql_tasks_service:
        condition: service_healthy
    networks:
      - pjp_mynetwork

  subscription_server_service:
    build:
      context: .
      dockerfile: subscription_service/Dockerfile
    container_name: subscription_service_container
    ports:
      - "50052:50052"
    depends_on:
      postgresql_subscription_service:
        condition: service_healthy
    networks:
      - pjp_mynetwork

  user_server_service:
    build:
      context: .
      dockerfile: user_service/Dockerfile
    container_name: user_service_container
    ports:
      - "50051:50051"
    depends_on:
      postgresql_user_service:
        condition: service_healthy
    networks:
      - pjp_mynetwork

  fastapi_orchestrator_service:
    container_name: fastapi_orchestrator_container
    build:
      context: .
      dockerfile: orchestrator_monolith/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      user_server_service:
        condition: service_started
      subscription_server_service:
        condition: service_started
      broker:
        condition: service_healthy
    networks:
      - pjp_mynetwork

  graphql_service:
    build:
      context: .
      dockerfile: graphql_service/Dockerfile
    container_name: graphql_container
    ports:
      - "5001:5001"
    networks:
      - pjp_mynetwork

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - pjp_mynetwork

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "broker:9092", "--list"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - pjp_mynetwork

networks:
  pjp_mynetwork:
    driver: bridge

volumes:
  postgresql_subscription_data:
    name: postgresql_subscription_volume

  postgresql_user_data:
    name: postgresql_user_volume

  postgresql_tasks_data:
    name: postgresql_tasks_volume