"""Remove subscription_type column from Subscription

Revision ID: 241343ce6369
Revises: b6f4b6e58b26
Create Date: 2025-01-27 13:23:02.575768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '241343ce6369'
down_revision: Union[str, None] = 'b6f4b6e58b26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'subscription_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('subscription_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
