"""update subscription model

Revision ID: b6f4b6e58b26
Revises: f56ff15260f4
Create Date: 2025-01-27 10:36:14.662474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6f4b6e58b26'
down_revision: Union[str, None] = 'f56ff15260f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subscriptions_email_key', 'subscriptions', type_='unique')
    op.drop_column('subscriptions', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('subscriptions_email_key', 'subscriptions', ['email'])
    # ### end Alembic commands ###
