"""Add unique=True for email in Subscription

Revision ID: e6b09700c4bb
Revises: 6b8fea121cc2
Create Date: 2025-01-08 09:34:24.183775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6b09700c4bb'
down_revision: Union[str, None] = '6b8fea121cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'subscriptions', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='unique')
    # ### end Alembic commands ###
