"""Update subscriptions table

Revision ID: f56ff15260f4
Revises: cfeb28537b4c
Create Date: 2025-01-23 12:07:22.810723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f56ff15260f4'
down_revision: Union[str, None] = 'cfeb28537b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'user_id')
    # ### end Alembic commands ###
