"""Change telephone to numbe

Revision ID: 50812f22696a
Revises: 76716cc7ef17
Create Date: 2024-12-04 16:51:27.345575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50812f22696a'
down_revision: Union[str, None] = '76716cc7ef17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('number', sa.Integer(), nullable=True))
    op.drop_column('users', 'telephone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telephone', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'number')
    # ### end Alembic commands ###
