"""Remove gender column from subscriptions

Revision ID: 9a80b7e7c3e1
Revises: d0697e7eb0ef
Create Date: 2024-12-06 17:17:59.353233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a80b7e7c3e1'
down_revision: Union[str, None] = 'd0697e7eb0ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
