FROM python:3.12-slim

WORKDIR /app

COPY ../requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH=/app/subscription_service/src/grpc_services/generated:$PYTHONPATH

COPY ../ /app/
COPY ./protos /app/protos

RUN python -m grpc_tools.protoc -I=protos --python_out=subscription_service/src/grpc_services/generated --grpc_python_out=subscription_service/src/grpc_services/generated protos/subscription.proto

EXPOSE 50052

CMD ["python", "subscription_service/subscription_service_server.py"]
