FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/requirements.txt

ENV PYTHONPATH=/app/user_service/src/grpc_services/generated:/app:/app/subscription_service/src/grpc_services/generated:$PYTHONPATH

RUN pip install --no-cache-dir -r requirements.txt

COPY ../ /app/

ENV PYTHONUNBUFFERED=1

EXPOSE 8001

CMD ["python", "graphql_service/graphql_api_start.py"]
