FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

CMD ["uvicorn", "src.api_services.fastapi_service:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

