services:
  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=user_management
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d user_management"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=test123
    depends_on:
      - postgres


  grpc-server:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 50051:50051
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

volumes:
  postgres_db:
    name: postgres_db